### ISSUE TITLE
 Cannot convert from 'MVVMToolkit.ViewModel' to 'System.ComponentModel.INotifyPropertyChanged

### ISSUE THREAD

**Issue by apilola** [bustedbunny/com.bustedbunny.mvvmtoolkit#2]
Including the package in an empty project 2021.3.26f1 in an empty project creates generates this error:

`Library\PackageCache\com.bustedbunny.mvvmtoolkit@1.0.0-pre.16\Runtime\Common\View\BaseView.cs(60,17): error CS1503: Argument 1: cannot convert from 'MVVMToolkit.ViewModel' to 'System.ComponentModel.INotifyPropertyChanged'`

Let me know if you need more information.

**Comment by bustedbunny** [comment]
You need 2022.2 at least. Older unity doesn't support Rosly 4.0.1 codegen.

**Comment by apilola** [comment]
Thanks that works.

**Comment by apilola** [comment]
Closing
